import { Noto_Sans } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';
import styles from './layout.module.css';
import { Header, Sidebar, Footer } from '@/components';
import { AppContextProvider } from '@/context/app.context';
import { prisma } from '@/lib/prisma';

const notoSans = Noto_Sans({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin', 'cyrillic'],
  variable: '--font-noto-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App - Home page',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await prisma.category.findMany();

  return (
    <html lang="en">
      <body className={notoSans.className}>
        <AppContextProvider categories={categories}>
          <div className={styles.wrapper}>
            <Header className={styles.header} />
            <Sidebar className={styles.sidebar} />
            <div className={styles.body}>{children}</div>
            <Footer className={styles.footer} />
          </div>
        </AppContextProvider>
      </body>
    </html>
  );
}
