import { Noto_Sans } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';
import styles from './layout.module.css';
import { Header, Sidebar, Footer } from '@/components';

const notoSans = Noto_Sans({
  weight: ['300', '400', '500', '700'], // ??
  subsets: ['latin', 'cyrillic'],
  variable: '--font-noto-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App - Home page',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSans.className}>
        <div className={styles.wrapper}>
          <Header className={styles.header} />
          <Sidebar className={styles.sidebar} />
          <div className={styles.body}>{children}</div>
          <Footer className={styles.footer} />
        </div>
      </body>
    </html>
  );
}
